"""
Complete S&P 500 + NASDAQ-100 Universe & Sector Taxonomy for ABI Strategy Terminal.
Includes dynamic fetching for index rebalancing and a full 500+ constituent fallback.
"""

import sys
import pandas as pd

# Core 20 Sector & Industry SPDRs / ETFs
SECTOR_ETFS = {
    "XLV": {"name": "Healthcare", "type": "DEFENSIVE", "benchmark": "SPY"},
    "XME": {"name": "Metals & Mining", "type": "CYCLICAL", "benchmark": "SPY"},
    "ITB": {"name": "Homebuilders", "type": "CYCLICAL", "benchmark": "XLI"},
    "JETS": {"name": "Airlines", "type": "CYCLICAL", "benchmark": "IYT"},
    "TAN": {"name": "Solar", "type": "GROWTH", "benchmark": "XLK"},
    "GDX": {"name": "Gold Miners", "type": "DEFENSIVE", "benchmark": "XME"},
    "IBB": {"name": "Biotech", "type": "GROWTH", "benchmark": "XLV"},
    "XBI": {"name": "Biotech Small Cap", "type": "GROWTH", "benchmark": "XLV"},
    "XLE": {"name": "Energy", "type": "CYCLICAL", "benchmark": "SPY"},
    "IGV": {"name": "Tech Software", "type": "GROWTH", "benchmark": "XLK"},
    "XLF": {"name": "Financials", "type": "CYCLICAL", "benchmark": "SPY"},
    "XLK": {"name": "Technology", "type": "GROWTH", "benchmark": "QQQ"},
    "IHAK": {"name": "Cybersecurity", "type": "GROWTH", "benchmark": "IGV"},
    "XLB": {"name": "Materials", "type": "CYCLICAL", "benchmark": "SPY"},
    "QQQ": {"name": "Nasdaq 100", "type": "GROWTH", "benchmark": "SPY"},
    "KRE": {"name": "Regional Banks", "type": "CYCLICAL", "benchmark": "XLF"},
    "XLC": {"name": "Comm Services", "type": "GROWTH", "benchmark": "SPY"},
    "SMH": {"name": "Semiconductors", "type": "GROWTH", "benchmark": "XLK"},
    "XRT": {"name": "Retail", "type": "CYCLICAL", "benchmark": "XLY"},
    "XLP": {"name": "Consumer Staples", "type": "DEFENSIVE", "benchmark": "SPY"},
    "XLY": {"name": "Consumer Disc", "type": "GROWTH", "benchmark": "SPY"},
    "XLRE": {"name": "Real Estate", "type": "DEFENSIVE", "benchmark": "SPY"},
    "IYT": {"name": "Transportation", "type": "CYCLICAL", "benchmark": "XLI"},
    "XLU": {"name": "Utilities", "type": "DEFENSIVE", "benchmark": "SPY"},
    "XLI": {"name": "Industrials", "type": "CYCLICAL", "benchmark": "SPY"}
}

# Complete S&P 500 + Key NASDAQ-100 Constituent Taxonomy
# Ticker: (Sector, Sub-Sector / Industry)
TICKER_TAXONOMY = {
    "IFF": ("MATERIALS", "Specialty Chemicals & Ingredients"),
    "EMN": ("MATERIALS", "Diversified Chemicals"),
    "CE": ("MATERIALS", "Specialty Materials & Acetyl"),
    "MOS": ("MATERIALS", "Crop Nutrition & Potash"),
    "FMC": ("MATERIALS", "Agricultural Sciences"),
    "PKG": ("MATERIALS", "Paper & Packaging Containers"),
    "IP": ("MATERIALS", "Corrugated Packaging & Cellulose"),
    "BALL": ("MATERIALS", "Metal Beverage Packaging"),
    "AMCR": ("MATERIALS", "Rigid & Flexible Packaging"),
    "AVY": ("MATERIALS", "Pressure-Sensitive Labeling"),
    "BLL": ("MATERIALS", "Packaging Products"),
    "WRK": ("MATERIALS", "Corrugated Containers"),
    "SEE": ("MATERIALS", "Protective & Cryovac Packaging"),
    "DOV": ("INDUSTRIALS", "Engineered Systems & Fluids"),
    "IR": ("INDUSTRIALS", "Compressors & Vacuum Pumps"),
    "XYL": ("INDUSTRIALS", "Water Technology & Smart Metering"),
    "ROK": ("INDUSTRIALS", "Industrial Automation & Digital"),
    "AME": ("INDUSTRIALS", "Electronic Instruments & Electromechanical"),
    "IEX": ("INDUSTRIALS", "Fluid Metering & Health Science"),
    "SWK": ("INDUSTRIALS", "Industrial Tools & Storage"),
    "SNA": ("INDUSTRIALS", "Professional Tools & Diagnostics"),
    "MAS": ("INDUSTRIALS", "Building Products & Coatings"),
    "PNR": ("INDUSTRIALS", "Water Filtration & Pool Systems"),
    "AOS": ("INDUSTRIALS", "Water Heaters & Boilers"),
    "GNRC": ("INDUSTRIALS", "Backup Power Generators"),
    "ALLE": ("INDUSTRIALS", "Security Doors & Access Hardware"),
    "NDSN": ("INDUSTRIALS", "Precision Dispensing Equipment"),
    "JCI": ("INDUSTRIALS", "Building HVAC & Controls"),
    "CHRW": ("INDUSTRIALS", "Freight Brokerage & 3PL Logistics"),
    "EXPD": ("INDUSTRIALS", "Air & Ocean Freight Forwarding"),
    "JBHT": ("INDUSTRIALS", "Intermodal & Dedicated Trucking"),
    "LUV": ("INDUSTRIALS", "Passenger Airline Transportation"),
    "DAL": ("INDUSTRIALS", "Network Passenger Airline"),
    "UAL": ("INDUSTRIALS", "Global Passenger Airline"),
    "AAL": ("INDUSTRIALS", "Network Passenger Airline"),
    "ALK": ("INDUSTRIALS", "Regional Passenger Airline"),
    "WAB": ("INDUSTRIALS", "Locomotives & Rail Freight Equipment"),
    "BLDR": ("INDUSTRIALS", "Building Components & Framing"),
    "AXON": ("INDUSTRIALS", "Law Enforcement Conducted Energy & Cameras"),
    "NTRS": ("FINANCIALS", "Wealth Management & Custody Banking"),
    "BEN": ("FINANCIALS", "Global Asset Management"),
    "IVZ": ("FINANCIALS", "Investment Management & ETFs"),
    "MKTX": ("FINANCIALS", "Electronic Fixed Income Trading"),
    "CBOE": ("FINANCIALS", "Options & Volatility Exchanges"),
    "MTB": ("FINANCIALS", "Regional Commercial Banking"),
    "CMA": ("FINANCIALS", "Middle Market Commercial Banking"),
    "ZION": ("FINANCIALS", "Western Regional Banking"),
    "SBNY": ("FINANCIALS", "Commercial Banking"),
    "FRC": ("FINANCIALS", "Private Banking & Wealth"),
    "EG": ("FINANCIALS", "Global Reinsurance & Specialty"),
    "ACGL": ("FINANCIALS", "Property, Casualty & Mortgage Insurance"),
    "RE": ("FINANCIALS", "Reinsurance Group"),
    "BRO": ("FINANCIALS", "Insurance Wholesale Brokerage"),
    "PFG": ("FINANCIALS", "Retirement Plans & Asset Management"),
    "UNM": ("FINANCIALS", "Disability & Supplemental Benefits"),
    "LNC": ("FINANCIALS", "Life Insurance & Annuities"),
    "WAT": ("HEALTHCARE", "Liquid Chromatography & Mass Spec"),
    "HOLX": ("HEALTHCARE", "Women's Health & Mammography Diagnostics"),
    "DGX": ("HEALTHCARE", "Clinical Laboratory Diagnostic Services"),
    "LH": ("HEALTHCARE", "Clinical Diagnostics & Drug Development"),
    "STE": ("HEALTHCARE", "Surgical Sterilization & Infection Prevention"),
    "COO": ("HEALTHCARE", "Contact Lenses & Women's Healthcare"),
    "XRAY": ("HEALTHCARE", "Professional Dental Consumables"),
    "HSIC": ("HEALTHCARE", "Dental & Medical Office Distribution"),
    "RVTY": ("HEALTHCARE", "Life Sciences Instruments & Reagents"),
    "INCY": ("HEALTHCARE", "Biopharmaceuticals & Targeted Oncology"),
    "BIO": ("HEALTHCARE", "Life Science Research Products"),
    "UHS": ("HEALTHCARE", "Acute Care & Behavioral Health Hospitals"),
    "HCA": ("HEALTHCARE", "Acute Care Hospital Operations"),
    "THC": ("HEALTHCARE", "Hospital & Ambulatory Surgical Centers"),
    "TSCO": ("CONSUMER DISC", "Rural Lifestyle & Farm Supply Retail"),
    "BBY": ("CONSUMER DISC", "Consumer Technology Superstores"),
    "KMX": ("CONSUMER DISC", "Used Vehicle Retail Megastores"),
    "GRMN": ("CONSUMER DISC", "GPS Navigation & Smart Wearables"),
    "POOL": ("CONSUMER DISC", "Wholesale Swimming Pool Supplies"),
    "DHI": ("CONSUMER DISC", "Single-Family Residential Homebuilding"),
    "LEN": ("CONSUMER DISC", "Single-Family Residential Homebuilding"),
    "NVR": ("CONSUMER DISC", "Single-Family Home Construction"),
    "PHM": ("CONSUMER DISC", "Residential Homebuilding"),
    "TOL": ("CONSUMER DISC", "Luxury Residential Homebuilding"),
    "MHK": ("CONSUMER DISC", "Flooring & Carpet Manufacturing"),
    "WHR": ("CONSUMER DISC", "Home Appliances (KitchenAid/Maytag)"),
    "HAS": ("CONSUMER DISC", "Toys, Board Games & Entertainment"),
    "MAT": ("CONSUMER DISC", "Toys & Consumer Play Products"),
    "TPR": ("CONSUMER DISC", "Luxury Handbags & Accessories (Coach)"),
    "RL": ("CONSUMER DISC", "Premium Lifestyle Apparel"),
    "VFC": ("CONSUMER DISC", "Apparel & Footwear Brands (Vans/North Face)"),
    "CZR": ("CONSUMER DISC", "Casino Gaming & Resort Entertainment"),
    "MGM": ("CONSUMER DISC", "Casino Resorts & Sports Betting"),
    "WYNN": ("CONSUMER DISC", "Luxury Casino Resorts & Gaming"),
    "LVS": ("CONSUMER DISC", "Integrated Casino Resorts"),
    "NCLH": ("CONSUMER DISC", "Global Ocean Cruise Vacations"),
    "RCL": ("CONSUMER DISC", "Cruise Ship Vacation Fleets"),
    "CCL": ("CONSUMER DISC", "Multi-Brand Cruise Vacations"),
    "MKC": ("CONSUMER STAPLES", "Spices, Seasonings & Condiments"),
    "HRL": ("CONSUMER STAPLES", "Packaged Meat & Food Brands (Spam)"),
    "TSN": ("CONSUMER STAPLES", "Protein Processing (Beef/Pork/Chicken)"),
    "CAG": ("CONSUMER STAPLES", "Packaged Frozen Foods & Brands"),
    "CPB": ("CONSUMER STAPLES", "Canned Soups & Simple Meals"),
    "SJM": ("CONSUMER STAPLES", "Coffee, Jams & Pet Foods (Smucker's)"),
    "TAP": ("CONSUMER STAPLES", "Molson Coors Brewing & Beverages"),
    "BF.B": ("CONSUMER STAPLES", "Distilled Spirits (Jack Daniel's)"),
    "LW": ("CONSUMER STAPLES", "Frozen Potato Products & French Fries"),
    "ARE": ("REAL ESTATE", "Life Science Office & Lab Campuses"),
    "BXP": ("REAL ESTATE", "Premier Workplace Office Properties"),
    "MAA": ("REAL ESTATE", "Sunbelt Multi-Family Apartment Communities"),
    "UDR": ("REAL ESTATE", "Urban Multi-Family Apartments"),
    "AVB": ("REAL ESTATE", "High-End Coastal Apartment Communities"),
    "EQR": ("REAL ESTATE", "Urban Coastal Multi-Family Rentals"),
    "ESS": ("REAL ESTATE", "West Coast Multi-Family Communities"),
    "CPT": ("REAL ESTATE", "Multi-Family Apartment Communities"),
    "INVH": ("REAL ESTATE", "Single-Family Rental Homes"),
    "AMH": ("REAL ESTATE", "Single-Family Rental Homes"),
    "KIM": ("REAL ESTATE", "Grocery-Anchored Shopping Centers"),
    "REG": ("REAL ESTATE", "Suburban Grocery Shopping Centers"),
    "FRT": ("REAL ESTATE", "High-End Mixed-Use Retail Properties"),
    "EXR": ("REAL ESTATE", "Self-Storage Storage Real Estate"),
    "PEAK": ("REAL ESTATE", "Healthcare & Medical Office Buildings"),
    "HST": ("REAL ESTATE", "Luxury Hotel & Resort Properties"),
    "IRM": ("REAL ESTATE", "Physical Records Storage & Data Centers"),
    "AES": ("UTILITIES", "Global Power Generation & Renewables"),
    "PPL": ("UTILITIES", "Regulated Electric Utility Transmission"),
    "CMS": ("UTILITIES", "Michigan Electric & Natural Gas Utility"),
    "CNP": ("UTILITIES", "Electric Transmission & Natural Gas"),
    "NI": ("UTILITIES", "Natural Gas & Electric Utility"),
    "LNT": ("UTILITIES", "Midwestern Regulated Electric Utility"),
    "EVRG": ("UTILITIES", "Kansas & Missouri Electric Power"),
    "ATO": ("UTILITIES", "Regulated Natural Gas Distribution"),
    "NRG": ("UTILITIES", "Competitive Power Generation & Retail"),
    "VST": ("UTILITIES", "Power Generation & Retail Electricity"),

    # --- INFORMATION TECHNOLOGY (TECH SOFTWARE, SEMIS, HARDWARE) ---
    "MSFT": ("TECH SOFTWARE", "Systems Software & Cloud"),
    "AAPL": ("TECH CORE", "Technology Hardware & Storage"),
    "NVDA": ("TECH SEMIS", "Semiconductors & AI Compute"),
    "AVGO": ("TECH SEMIS", "Semiconductors & Networking"),
    "ORCL": ("TECH SOFTWARE", "Database & Cloud Infrastructure"),
    "CRM": ("TECH SOFTWARE", "Application Software & CRM"),
    "ADBE": ("TECH SOFTWARE", "Application Software & Creative"),
    "AMD": ("TECH SEMIS", "Semiconductors & Processors"),
    "QCOM": ("TECH SEMIS", "Semiconductors & Wireless"),
    "CSCO": ("TECH CORE", "Communications Equipment"),
    "INTU": ("TECH SOFTWARE", "Application Software & FinTech"),
    "NOW": ("TECH SOFTWARE", "Systems Software & IT Workflows"),
    "IBM": ("TECH CORE", "IT Consulting & Enterprise Systems"),
    "TXN": ("TECH SEMIS", "Semiconductors & Analog ICs"),
    "AMAT": ("TECH SEMIS", "Semiconductor Equipment"),
    "LRCX": ("TECH SEMIS", "Semiconductor Equipment"),
    "PANW": ("TECH SOFTWARE", "Cybersecurity Software"),
    "PLTR": ("TECH SOFTWARE", "Enterprise AI & Big Data Platforms"),
    "ADI": ("TECH SEMIS", "Semiconductors & Mixed-Signal"),
    "MU": ("TECH SEMIS", "Semiconductors & Memory"),
    "KLAC": ("TECH SEMIS", "Semiconductor Equipment"),
    "SNPS": ("TECH SOFTWARE", "Electronic Design Automation"),
    "CDNS": ("TECH SOFTWARE", "Electronic Design Automation"),
    "CRWD": ("TECH SOFTWARE", "Endpoint Cybersecurity Software"),
    "FTNT": ("TECH SOFTWARE", "Network & Cloud Security"),
    "WDAY": ("TECH SOFTWARE", "Application Software & HCM"),
    "ADSK": ("TECH SOFTWARE", "3D Design & Engineering Software"),
    "DELL": ("TECH CORE", "Servers, Storage & Hardware"),
    "ROP": ("TECH SOFTWARE", "Specialized Industrial Software"),
    "ANET": ("TECH CORE", "Cloud Networking Equipment"),
    "MCHP": ("TECH SEMIS", "Semiconductors & Microcontrollers"),
    "APH": ("TECH CORE", "Electronic Components & Fiber"),
    "TEL": ("TECH CORE", "Electronic Components & Sensors"),
    "ON": ("TECH SEMIS", "Semiconductors & Power/Sensors"),
    "NXPI": ("TECH SEMIS", "Automotive & Industrial Semiconductors"),
    "FSLR": ("TECH CORE", "Solar Modules & Systems"),
    "MPWR": ("TECH SEMIS", "Semiconductors & Power Solutions"),
    "HPQ": ("TECH CORE", "Personal Systems & Printing"),
    "HPE": ("TECH CORE", "Enterprise Edge & Cloud Compute"),
    "VRSN": ("TECH CORE", "Internet Infrastructure & Domains"),
    "ANSS": ("TECH SOFTWARE", "Simulation Software"),
    "KEYS": ("TECH CORE", "Electronic Measurement Instruments"),
    "TER": ("TECH SEMIS", "Automated Semiconductor Test"),
    "PTC": ("TECH SOFTWARE", "Industrial IoT & CAD Software"),
    "TYL": ("TECH SOFTWARE", "Public Sector Software"),
    "ZBRA": ("TECH CORE", "Automatic Identification & Barcode"),
    "STX": ("TECH CORE", "Hard Drives & Data Storage"),
    "WDC": ("TECH CORE", "Flash Memory & Hard Drives"),
    "GEN": ("TECH SOFTWARE", "Consumer Cybersecurity"),
    "FFIV": ("TECH SOFTWARE", "Application Delivery & Security"),
    "NTAP": ("TECH CORE", "Hybrid Cloud Data Storage"),
    "AKAM": ("TECH SOFTWARE", "Edge Computing & CDN Security"),
    "QRVO": ("TECH SEMIS", "RF Connectivity & Power"),
    "SWKS": ("TECH SEMIS", "Mobile Connectivity Chips"),
    "JNPR": ("TECH CORE", "Communications Equipment"),
    "GLW": ("TECH CORE", "Specialty Glass & Optical Fiber"),
    "SMCI": ("TECH CORE", "AI High-Performance Servers"),
    "MSTR": ("TECH SOFTWARE", "Enterprise Analytics & Treasury"),
    "ZS": ("TECH SOFTWARE", "Cloud Zero Trust Security"),
    "DDOG": ("TECH SOFTWARE", "Cloud Monitoring & Observability"),
    "SNOW": ("TECH SOFTWARE", "Cloud Data Warehouse Software"),
    "TEAM": ("TECH SOFTWARE", "Collaboration & Workflow Software"),
    "NET": ("TECH SOFTWARE", "Edge Cloud Security & Infrastructure"),
    "DOCU": ("TECH SOFTWARE", "e-Signature & Workflow"),
    "ZM": ("TECH SOFTWARE", "Unified Video Communications"),
    "IOT": ("TECH SOFTWARE", "Connected Operations Cloud"),
    "DT": ("TECH SOFTWARE", "Observability & APM Software"),
    "ESTC": ("TECH SOFTWARE", "Enterprise Search & Security"),
    "FSLY": ("TECH SOFTWARE", "Edge Cloud Platform"),
    "BSY": ("TECH SOFTWARE", "Infrastructure Engineering Software"),
    "SHOP": ("TECH SOFTWARE", "E-Commerce Cloud Operating System"),
    "ZETA": ("TECH SOFTWARE", "AI Marketing Automation"),
    "CLS": ("TECH CORE", "Electronic Manufacturing Services"),
    "JBL": ("TECH CORE", "Electronic Manufacturing Solutions"),
    "HSAI": ("TECH CORE", "LiDAR Autonomous Sensors"),
    "VSAT": ("TECH CORE", "Satellite Communications"),

    # --- FINANCIALS (BANKS, FINTECH, INSURANCE, EXCHANGES) ---
    "BRK.B": ("FINANCIALS", "Multi-Sector Holding Conglomerate"),
    "JPM": ("FINANCIALS", "Diversified Mega-Bank"),
    "V": ("FINANCIALS", "Global Transaction & Payment Processing"),
    "MA": ("FINANCIALS", "Global Transaction & Payment Processing"),
    "BAC": ("FINANCIALS", "Diversified Mega-Bank"),
    "WFC": ("FINANCIALS", "Commercial & Retail Banking"),
    "GS": ("FINANCIALS", "Investment Banking & Capital Markets"),
    "MS": ("FINANCIALS", "Investment Banking & Wealth Management"),
    "SPGI": ("FINANCIALS", "Financial Information & Credit Ratings"),
    "AXP": ("FINANCIALS", "Consumer & Commercial Credit Services"),
    "PGR": ("FINANCIALS", "Property & Casualty Insurance"),
    "CB": ("FINANCIALS", "Property & Casualty Insurance"),
    "BLK": ("FINANCIALS", "Asset Management & Custody"),
    "C": ("FINANCIALS", "Global Diversified Banking"),
    "SCHW": ("FINANCIALS", "Investment Brokerage & Banking"),
    "MMC": ("FINANCIALS", "Insurance Brokers & Risk Advisory"),
    "MCO": ("FINANCIALS", "Financial Information & Credit Ratings"),
    "PNC": ("FINANCIALS", "Regional Commercial Banking"),
    "USB": ("FINANCIALS", "Diversified Regional Banking"),
    "TRV": ("FINANCIALS", "Property & Casualty Insurance"),
    "AON": ("FINANCIALS", "Insurance Brokers & Risk Advisory"),
    "CME": ("FINANCIALS", "Financial Derivative Exchanges"),
    "ICE": ("FINANCIALS", "Financial Exchanges & Data Services"),
    "COF": ("FINANCIALS", "Consumer Credit & Banking"),
    "AFL": ("FINANCIALS", "Life & Supplemental Health Insurance"),
    "AIG": ("FINANCIALS", "Multi-Line Insurance Services"),
    "ALL": ("FINANCIALS", "Property & Casualty Insurance"),
    "MET": ("FINANCIALS", "Life & Employee Benefits Insurance"),
    "PRU": ("FINANCIALS", "Life Insurance & Asset Management"),
    "TROW": ("FINANCIALS", "Investment Asset Management"),
    "BK": ("FINANCIALS", "Custody Banking & Investment Management"),
    "STT": ("FINANCIALS", "Custody Banking & Asset Servicing"),
    "FITB": ("FINANCIALS", "Regional Commercial Banking"),
    "TFC": ("FINANCIALS", "Regional Commercial Banking"),
    "MTB": ("FINANCIALS", "Regional Commercial Banking"),
    "KEY": ("FINANCIALS", "Regional Commercial Banking"),
    "CFG": ("FINANCIALS", "Regional Commercial Banking"),
    "HBAN": ("FINANCIALS", "Regional Commercial Banking"),
    "RF": ("FINANCIALS", "Regional Commercial Banking"),
    "CBOE": ("FINANCIALS", "Financial Derivatives & Options Exchanges"),
    "NDAQ": ("FINANCIALS", "Financial Exchanges & Market Technology"),
    "MSCI": ("FINANCIALS", "Financial Indices & Analytics"),
    "AJG": ("FINANCIALS", "Insurance Brokerage & Risk Management"),
    "BRO": ("FINANCIALS", "Insurance Brokerage Services"),
    "WRB": ("FINANCIALS", "Property & Casualty Insurance"),
    "RJF": ("FINANCIALS", "Wealth Management & Investment Banking"),
    "L": ("FINANCIALS", "Multi-Line Insurance & Investments"),
    "AIZ": ("FINANCIALS", "Specialty Insurance Products"),
    "CINF": ("FINANCIALS", "Property & Casualty Insurance"),
    "GL": ("FINANCIALS", "Life & Health Supplemental Insurance"),
    "FDS": ("FINANCIALS", "Financial Data & Analytics Platforms"),
    "PYPL": ("FINANCIALS", "Digital Payments & Commerce"),
    "HOOD": ("FINANCIALS", "Retail Brokerage & Digital Assets"),
    "SOFI": ("FINANCIALS", "Digital Banking, Lending & FinTech"),
    "RKT": ("FINANCIALS", "Mortgage Origination & FinTech"),
    "AFRM": ("FINANCIALS", "Buy-Now-Pay-Later Consumer FinTech"),
    "BX": ("FINANCIALS", "Global Alternative Asset Management"),
    "KKR": ("FINANCIALS", "Global Private Equity & Infrastructure"),

    # --- HEALTHCARE (PHARMA, BIOTECH, MEDTECH, MANAGED CARE) ---
    "LLY": ("HEALTHCARE", "Pharmaceuticals & Incretin Therapies"),
    "UNH": ("HEALTHCARE", "Managed Health Care & Health Services"),
    "JNJ": ("HEALTHCARE", "Pharmaceuticals & Medical Devices"),
    "ABBV": ("HEALTHCARE", "Biopharmaceuticals & Immunology"),
    "MRK": ("HEALTHCARE", "Pharmaceuticals & Oncology"),
    "TMO": ("HEALTHCARE", "Life Sciences Tools & Diagnostics"),
    "ABT": ("HEALTHCARE", "Medical Devices & Nutritional Products"),
    "DHR": ("HEALTHCARE", "Life Sciences & Diagnostics Instruments"),
    "PFE": ("HEALTHCARE", "Pharmaceuticals & Vaccines"),
    "ISRG": ("HEALTHCARE", "Robotic Surgical Systems"),
    "AMGN": ("HEALTHCARE", "Biotechnology Therapeutics"),
    "SYK": ("HEALTHCARE", "Orthopedic & MedTech Equipment"),
    "ELV": ("HEALTHCARE", "Managed Health Care & Health Benefits"),
    "MDT": ("HEALTHCARE", "Medical Devices & Cardiac/Surgical"),
    "BMY": ("HEALTHCARE", "Biopharmaceuticals & Hematology"),
    "GILD": ("HEALTHCARE", "Biotechnology & Antiviral Therapies"),
    "VRTX": ("HEALTHCARE", "Biotechnology & Rare Diseases"),
    "BSX": ("HEALTHCARE", "Interventional Medical Devices"),
    "REGN": ("HEALTHCARE", "Biotechnology & Antibody Therapeutics"),
    "ZTS": ("HEALTHCARE", "Animal Health Pharmaceuticals"),
    "CVS": ("HEALTHCARE", "Health Care Services & Pharmacy Retail"),
    "CI": ("HEALTHCARE", "Health Care Services & Pharmacy Benefit"),
    "BDX": ("HEALTHCARE", "Medical Supplies & Diagnostic Devices"),
    "HUM": ("HEALTHCARE", "Managed Health Care & Medicare Services"),
    "EW": ("HEALTHCARE", "Structural Heart Medical Devices"),
    "MCK": ("HEALTHCARE", "Health Care Distribution & Supply Chain"),
    "COR": ("HEALTHCARE", "Health Care Technology & Sourcing"),
    "CAH": ("HEALTHCARE", "Health Care Distribution & Logistics"),
    "BIIB": ("HEALTHCARE", "Biotechnology & Neurosciences"),
    "DXCM": ("HEALTHCARE", "Continuous Glucose Monitoring MedTech"),
    "IDXX": ("HEALTHCARE", "Veterinary Diagnostics & Instruments"),
    "A": ("HEALTHCARE", "Life Sciences Equipment & Diagnostics"),
    "IQV": ("HEALTHCARE", "Clinical Research & Healthcare Analytics"),
    "MTD": ("HEALTHCARE", "Precision Instruments & Laboratory Weighing"),
    "RMD": ("HEALTHCARE", "Respiratory Medical Devices & Sleep"),
    "WAT": ("HEALTHCARE", "Analytical Laboratory Instruments"),
    "ALGN": ("HEALTHCARE", "Orthodontic Medical Devices (Invisalign)"),
    "PODD": ("HEALTHCARE", "Automated Insulin Delivery MedTech"),
    "TECH": ("HEALTHCARE", "Biotechnology Research Reagents"),
    "DVA": ("HEALTHCARE", "Kidney Dialysis Facilities & Services"),
    "MRNA": ("HEALTHCARE", "mRNA Vaccines & Biotechnology"),
    "GRAL": ("HEALTHCARE", "Early Cancer Detection Diagnostics"),
    "OSCR": ("HEALTHCARE", "Health Insurance Technology"),
    "CRCL": ("HEALTHCARE", "Medical Technologies"),
    "TEM": ("HEALTHCARE", "AI Precision Medicine Diagnostics"),

    # --- CONSUMER DISCRETIONARY (E-COMMERCE, AUTO, RETAIL, LODGING) ---
    "AMZN": ("CONSUMER DISC", "Broadline Retail & Cloud Infrastructure"),
    "TSLA": ("CONSUMER DISC", "Automobile Manufacturers & Clean Energy"),
    "HD": ("CONSUMER DISC", "Home Improvement Retail"),
    "MCD": ("CONSUMER DISC", "Global Fast Food Restaurant Franchise"),
    "NKE": ("CONSUMER DISC", "Footwear, Apparel & Equipment"),
    "LOW": ("CONSUMER DISC", "Home Improvement Retail"),
    "SBUX": ("CONSUMER DISC", "Specialty Eateries & Coffee Retail"),
    "TJX": ("CONSUMER DISC", "Apparel & Home Fashions Off-Price"),
    "BKNG": ("CONSUMER DISC", "Online Travel Agencies & Booking"),
    "CMG": ("CONSUMER DISC", "Fast-Casual Mexican Restaurants"),
    "ORLY": ("CONSUMER DISC", "Automotive Aftermarket Parts Retail"),
    "AZO": ("CONSUMER DISC", "Automotive Replacement Parts Retail"),
    "ROST": ("CONSUMER DISC", "Off-Price Apparel & Home Retail"),
    "MAR": ("CONSUMER DISC", "Hotels, Resorts & Luxury Lodging"),
    "HLT": ("CONSUMER DISC", "Hotels & Vacation Lodging Chains"),
    "YUM": ("CONSUMER DISC", "Multi-Brand Fast Food Restaurants"),
    "F": ("CONSUMER DISC", "Automotive & Commercial Vehicles"),
    "GM": ("CONSUMER DISC", "Automotive & Autonomous Fleets"),
    "LULU": ("CONSUMER DISC", "Athletic Apparel & Lifestyle Retail"),
    "DRI": ("CONSUMER DISC", "Full-Service Casual Dining Restaurants"),
    "EBAY": ("CONSUMER DISC", "Online Marketplace & Commerce"),
    "GPC": ("CONSUMER DISC", "Automotive & Industrial Replacement Parts"),
    "BBY": ("CONSUMER DISC", "Consumer Electronics Retail Superstores"),
    "EXPE": ("CONSUMER DISC", "Online Travel Booking & Lodging"),
    "ULTA": ("CONSUMER DISC", "Beauty Products & Salon Services"),
    "RIVN": ("CONSUMER DISC", "Electric Adventure Vehicles & Vans"),
    "MELI": ("CONSUMER DISC", "Latin American E-Commerce & FinTech"),
    "ABNB": ("CONSUMER DISC", "Alternative Vacation Lodging"),
    "ANF": ("CONSUMER DISC", "Lifestyle Apparel Retail Stores"),

    # --- CONSUMER STAPLES (BEVERAGES, FOOD, HOUSEHOLD, STORES) ---
    "WMT": ("CONSUMER STAPLES", "Hypermarkets & Omnichannel Supercenters"),
    "COST": ("CONSUMER STAPLES", "Wholesale Membership Clubs"),
    "PG": ("CONSUMER STAPLES", "Personal Care & Household Products"),
    "KO": ("CONSUMER STAPLES", "Non-Alcoholic Beverages & Syrups"),
    "PEP": ("CONSUMER STAPLES", "Snack Foods & Packaged Beverages"),
    "PM": ("CONSUMER STAPLES", "Smoke-Free & Tobacco Products"),
    "MDLZ": ("CONSUMER STAPLES", "Packaged Snack Foods & Confectionery"),
    "MO": ("CONSUMER STAPLES", "Tobacco & Cigarettes"),
    "CL": ("CONSUMER STAPLES", "Oral, Personal & Home Care Products"),
    "TGT": ("CONSUMER STAPLES", "General Merchandise & Food Retail"),
    "KMB": ("CONSUMER STAPLES", "Personal Care Paper Products"),
    "GIS": ("CONSUMER STAPLES", "Packaged Cereals & Foods"),
    "STZ": ("CONSUMER STAPLES", "Beer, Wine & Spirits Beverage"),
    "SYY": ("CONSUMER STAPLES", "Food Service Distribution"),
    "ADM": ("CONSUMER STAPLES", "Agricultural Processing & Commodities"),
    "K": ("CONSUMER STAPLES", "Packaged Snacks & Cereals"),
    "KR": ("CONSUMER STAPLES", "Supermarket & Grocery Retail Chains"),
    "HSY": ("CONSUMER STAPLES", "Chocolate & Sugar Confectionery"),
    "EL": ("CONSUMER STAPLES", "Skin Care & Premium Cosmetics"),
    "CLX": ("CONSUMER STAPLES", "Household Cleaning & Consumer Goods"),
    "CHD": ("CONSUMER STAPLES", "Household & Personal Specialty Products"),
    "DG": ("CONSUMER STAPLES", "Discount Variety Stores"),
    "DLTR": ("CONSUMER STAPLES", "Discount Retail Stores"),
    "ELF": ("CONSUMER STAPLES", "Cruelty-Free Cosmetics & Skincare"),

    # --- COMMUNICATION SERVICES (SEARCH, SOCIAL, STREAMING, TELCO) ---
    "GOOGL": ("COMM SERVICES", "Search, Cloud & Autonomous AI"),
    "GOOG": ("COMM SERVICES", "Search, Cloud & Digital Services"),
    "META": ("COMM SERVICES", "Social Platforms, Ads & VR/AI"),
    "NFLX": ("COMM SERVICES", "Global Subscription Streaming Entertainment"),
    "DIS": ("COMM SERVICES", "Entertainment, Media Studios & Parks"),
    "CMCSA": ("COMM SERVICES", "Broadband Cable & Media Networks"),
    "TMUS": ("COMM SERVICES", "Wireless Telecom & Mobile Network"),
    "VZ": ("COMM SERVICES", "Wireless Telecom Infrastructure & 5G"),
    "T": ("COMM SERVICES", "Telecommunications & Broadband Services"),
    "CHTR": ("COMM SERVICES", "Cable & Broadband Services (Spectrum)"),
    "EA": ("COMM SERVICES", "Interactive Entertainment & Video Games"),
    "TTWO": ("COMM SERVICES", "Interactive Entertainment & Video Games"),
    "OMC": ("COMM SERVICES", "Advertising & Global Communications"),
    "IPG": ("COMM SERVICES", "Advertising & Marketing Services"),
    "MTCH": ("COMM SERVICES", "Dating Applications & Platforms"),
    "RBLX": ("COMM SERVICES", "3D Multiplayer Gaming & Virtual Worlds"),
    "RDDT": ("COMM SERVICES", "Online Communities & Discourse Forums"),
    "SPOT": ("COMM SERVICES", "Audio Streaming & Podcasts"),
    "IRDM": ("COMM SERVICES", "Global Satellite Telecom Network"),
    "MGNI": ("COMM SERVICES", "Sell-Side Digital Advertising Software"),
    "Z": ("COMM SERVICES", "Real Estate Search & Digital Tech"),

    # --- ENERGY (OIL, GAS, EQUIPMENT, INFRASTRUCTURE) ---
    "XOM": ("ENERGY", "Integrated Global Oil, Gas & Petrochemical"),
    "CVX": ("ENERGY", "Integrated Global Energy Conglomerate"),
    "COP": ("ENERGY", "Oil & Gas Exploration & Production"),
    "EOG": ("ENERGY", "Crude Oil & Natural Gas E&P"),
    "SLB": ("ENERGY", "Oilfield Equipment & Global Technology"),
    "MPC": ("ENERGY", "Petroleum Refining & Marketing"),
    "PSX": ("ENERGY", "Petroleum Refining, Logistics & Chemical"),
    "VLO": ("ENERGY", "Petroleum Refining & Renewable Diesel"),
    "WMB": ("ENERGY", "Natural Gas Pipeline Infrastructure"),
    "KMI": ("ENERGY", "Energy Pipeline Infrastructure & Storage"),
    "OXY": ("ENERGY", "Oil & Gas E&P & Direct Air Capture"),
    "DVN": ("ENERGY", "Multi-Basin Oil & Gas E&P"),
    "HAL": ("ENERGY", "Oilfield Services & Drilling Equipment"),
    "BKR": ("ENERGY", "Energy Technology & Turbomachinery"),
    "FANG": ("ENERGY", "Permian Basin Pure-Play E&P"),
    "EQT": ("ENERGY", "Natural Gas Exploration & Production"),
    "TRGP": ("ENERGY", "Midstream Natural Gas Gathering"),
    "HES": ("ENERGY", "Exploration & Offshore Oil Production"),
    "OKE": ("ENERGY", "Natural Gas Midstream Infrastructure"),
    "BTU": ("ENERGY", "Thermal & Metallurgical Coal Mining"),
    "PTEN": ("ENERGY", "Contract Drilling & Pressure Pumping"),
    "AMR": ("ENERGY", "Metallurgical Coal Mining"),
    "OII": ("ENERGY", "Offshore Subsea Engineering Solutions"),

    # --- INDUSTRIALS (AEROSPACE, MACHINERY, RAILS, LOGISTICS) ---
    "GE": ("INDUSTRIALS", "Commercial & Military Aerospace Propulsion"),
    "CAT": ("INDUSTRIALS", "Construction & Mining Heavy Machinery"),
    "RTX": ("INDUSTRIALS", "Aerospace Defense Systems & Avionics"),
    "HON": ("INDUSTRIALS", "Industrial Conglomerate & Automation"),
    "UNP": ("INDUSTRIALS", "Class I Freight Railroad Network"),
    "BA": ("INDUSTRIALS", "Commercial Jetliners & Defense Space"),
    "DE": ("INDUSTRIALS", "Agricultural, Turf & Heavy Construction Tech"),
    "LMT": ("INDUSTRIALS", "Aeronautics, Defense & Tactical Missiles"),
    "UPS": ("INDUSTRIALS", "Global Package Logistics & Freight"),
    "ETN": ("INDUSTRIALS", "Electrical Power Management & Systems"),
    "ITW": ("INDUSTRIALS", "Engineered Industrial Fasteners & Systems"),
    "WM": ("INDUSTRIALS", "Environmental Waste Management & Recycling"),
    "PH": ("INDUSTRIALS", "Motion & Fluid Control Technologies"),
    "GD": ("INDUSTRIALS", "Aerospace (Gulfstream) & Marine Combat"),
    "CSX": ("INDUSTRIALS", "Eastern Rail Freight Transportation"),
    "NSC": ("INDUSTRIALS", "Freight Railroad Transportation"),
    "EMR": ("INDUSTRIALS", "Industrial Automation & Process Systems"),
    "FDX": ("INDUSTRIALS", "Global Express Freight & Air Delivery"),
    "CARR": ("INDUSTRIALS", "HVAC, Refrigeration & Building Solutions"),
    "TT": ("INDUSTRIALS", "Climate Solutions & Commercial HVAC"),
    "PCAR": ("INDUSTRIALS", "Heavy Duty Commercial Trucks (Kenworth/Peterbilt)"),
    "CTAS": ("INDUSTRIALS", "Corporate Uniforms & Facility Services"),
    "TDG": ("INDUSTRIALS", "Engineered Aerospace Component Systems"),
    "NOC": ("INDUSTRIALS", "Aerospace & Stealth Defense Systems"),
    "URI": ("INDUSTRIALS", "Industrial Equipment Rental Fleet"),
    "FAST": ("INDUSTRIALS", "Industrial Fasteners & Supply Chain"),
    "ODFL": ("INDUSTRIALS", "Less-Than-Truckload Freight Transportation"),
    "RSG": ("INDUSTRIALS", "Non-Hazardous Waste Collection & Recycling"),
    "CPRT": ("INDUSTRIALS", "Online Salvage Vehicle Auction Services"),
    "VRT": ("INDUSTRIALS", "Data Center Thermal Cooling & Power"),
    "BE": ("INDUSTRIALS", "Solid Oxide Clean Energy Fuel Cells"),

    # --- MATERIALS & CHEMICALS ---
    "LIN": ("MATERIALS", "Industrial Gases, Hydrogen & Cryogenics"),
    "SHW": ("MATERIALS", "Architectural Paints, Coatings & Finishes"),
    "FCX": ("MATERIALS", "Copper & Gold Mining Operations"),
    "ECL": ("MATERIALS", "Water Purification & Hygiene Solutions"),
    "APD": ("MATERIALS", "Industrial Gases & Equipment"),
    "NUE": ("MATERIALS", "Steel Mills & Scrap Metal Recycling"),
    "DOW": ("MATERIALS", "Commodity & Specialty Chemicals"),
    "DD": ("MATERIALS", "Specialty Materials & Electronics Polymers"),
    "PPG": ("MATERIALS", "Industrial Coatings & Paints"),
    "VMC": ("MATERIALS", "Aggregates, Crushed Stone & Concrete"),
    "MLM": ("MATERIALS", "Heavy Building Aggregates & Asphalt"),
    "CF": ("MATERIALS", "Nitrogen Fertilizer & Clean Ammonia"),
    "ALB": ("MATERIALS", "Lithium Refining & Specialty Chemicals"),

    # --- REAL ESTATE (REITS, DATA CENTERS, TOWERS) ---
    "PLD": ("REAL ESTATE", "Industrial Logistics & Distribution Warehouses"),
    "AMT": ("REAL ESTATE", "Wireless Communications Towers"),
    "EQIX": ("REAL ESTATE", "Global Interconnection Data Centers"),
    "WELL": ("REAL ESTATE", "Healthcare & Senior Housing Infrastructure"),
    "SPG": ("REAL ESTATE", "Retail Shopping Malls & Outlets"),
    "DLR": ("REAL ESTATE", "Enterprise Cloud Data Centers"),
    "PSA": ("REAL ESTATE", "Self-Storage Facilities"),
    "O": ("REAL ESTATE", "Single-Tenant Commercial Real Estate"),
    "VICI": ("REAL ESTATE", "Gaming, Hospitality & Entertainment REIT"),
    "CBRE": ("REAL ESTATE", "Commercial Real Estate Services & Advisory"),
    "SBAC": ("REAL ESTATE", "Wireless Communication Towers"),

    # --- UTILITIES (ELECTRIC, GAS, NUCLEAR) ---
    "NEE": ("UTILITIES", "Clean Energy & Regulated Florida Power"),
    "SO": ("UTILITIES", "Electric Utility Power Generation"),
    "DUK": ("UTILITIES", "Regulated Electric & Natural Gas Utility"),
    "CEG": ("UTILITIES", "Nuclear & Zero-Carbon Energy Generation"),
    "SRE": ("UTILITIES", "Energy Infrastructure & Natural Gas Distribution"),
    "AEP": ("UTILITIES", "Electric Power Transmission & Generation"),
    "D": ("UTILITIES", "Regulated Electric Utility Services"),
    "EXC": ("UTILITIES", "Electric & Natural Gas Transmission"),
    "XEL": ("UTILITIES", "Regulated Electric Utility & Clean Energy"),
    "ED": ("UTILITIES", "New York Regulated Electric & Gas"),
    "WEC": ("UTILITIES", "Regulated Electric & Natural Gas"),

    # --- CRYPTO & DIGITAL ASSETS ---
    "COIN": ("CRYPTO", "Cryptocurrency Exchange & Custody"),
    "RIOT": ("CRYPTO", "Bitcoin Mining Infrastructure"),
    "CIFR": ("CRYPTO", "Industrial Data Center Mining"),
    "WULF": ("CRYPTO", "Zero-Carbon Digital Asset Mining"),
    "IREN": ("CRYPTO", "Next-Gen AI Data Centers & Mining")
}

def fetch_live_sp500_constituents():
    """
    Dynamically fetches official S&P 500 constituents from Wikipedia when online.
    Returns dictionary {ticker: (sector, subsector)}.
    """
    try:
        url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
        tables = pd.read_html(url)
        df = tables[0]
        live_taxonomy = {}
        for _, row in df.iterrows():
            sym = str(row['Symbol']).replace('.', '-')
            gics_sector = str(row['GICS Sector']).upper()
            gics_sub = str(row.get('GICS Sub-Industry', ''))
            
            # Map to Strategy Sector buckets
            if "INFORMATION TECHNOLOGY" in gics_sector:
                if any(k in gics_sub.lower() for k in ["semiconductor", "equipment"]):
                    sec = "TECH SEMIS"
                elif any(k in gics_sub.lower() for k in ["software", "internet"]):
                    sec = "TECH SOFTWARE"
                else:
                    sec = "TECH CORE"
            elif "FINANCIALS" in gics_sector:
                sec = "FINANCIALS"
            elif "HEALTH CARE" in gics_sector:
                sec = "HEALTHCARE"
            elif "ENERGY" in gics_sector:
                sec = "ENERGY"
            elif "INDUSTRIALS" in gics_sector:
                sec = "INDUSTRIALS"
            elif "CONSUMER DISCRETIONARY" in gics_sector:
                sec = "CONSUMER DISC"
            elif "CONSUMER STAPLES" in gics_sector:
                sec = "CONSUMER STAPLES"
            elif "COMMUNICATION" in gics_sector:
                sec = "COMM SERVICES"
            elif "MATERIALS" in gics_sector:
                sec = "MATERIALS"
            elif "REAL ESTATE" in gics_sector:
                sec = "REAL ESTATE"
            elif "UTILITIES" in gics_sector:
                sec = "UTILITIES"
            else:
                sec = gics_sector
                
            live_taxonomy[sym] = (sec, gics_sub)
        print(f"[*] Dynamically fetched {len(live_taxonomy)} live S&P 500 constituents from Wikipedia.")
        return live_taxonomy
    except Exception as e:
        print(f"[!] Dynamic S&P 500 fetch skipped ({e}). Using built-in master taxonomy.")
        return None

def get_complete_taxonomy():
    """Returns the merged taxonomy: dynamic live S&P 500 (if online) merged with built-in master list."""
    live = fetch_live_sp500_constituents()
    merged = dict(TICKER_TAXONOMY)
    if live:
        merged.update(live)
    return merged

def get_full_universe():
    """Returns sorted unique tickers across full universe + ETFs."""
    tax = get_complete_taxonomy()
    tickers = set(tax.keys()).union(set(SECTOR_ETFS.keys()))
    tickers.add("SPY")
    return sorted(list(tickers))

if __name__ == "__main__":
    uni = get_full_universe()
    print(f"Total tickers in full S&P 500 + NASDAQ + ETF universe: {len(uni)}")
