"""
Universe & Sector Telemetry Mappings for ABI Strategy Terminal.
Covers S&P 500, NASDAQ-100, Mega-Caps, and Core Sector ETFs.
"""

SECTOR_ETFS = {
    "GDX": {"name": "Gold Miners", "type": "DEFENSIVE", "benchmark": "XME"},
    "IBB": {"name": "Biotech", "type": "GROWTH", "benchmark": "XLV"},
    "XBI": {"name": "Biotech Small Cap", "type": "GROWTH", "benchmark": "XLV"},
    "XLE": {"name": "Energy", "type": "CYCLICAL", "benchmark": "SPY"},
    "IGV": {"name": "Tech Software", "type": "GROWTH", "benchmark": "XLK"},
    "XLF": {"name": "Financials", "type": "CYCLICAL", "benchmark": "SPY"},
    "XLK": {"name": "Technology", "type": "GROWTH", "benchmark": "QQQ"},
    "IHAK": {"name": "Cybersecurity", "type": "GROWTH", "benchmark": "IGV"},
    "XLB": {"name": "Materials", "type": "CYCLICAL", "benchmark": "SPY"},
    "QQQ": {"name": "Nasdaq 100", "type": "GROWTH", "benchmark": "SPY"},
    "KRE": {"name": "Regional Banks", "type": "CYCLICAL", "benchmark": "XLF"},
    "XLC": {"name": "Comm Services", "type": "GROWTH", "benchmark": "SPY"},
    "SMH": {"name": "Semiconductors", "type": "GROWTH", "benchmark": "XLK"},
    "XRT": {"name": "Retail", "type": "CYCLICAL", "benchmark": "XLY"},
    "XLP": {"name": "Consumer Staples", "type": "DEFENSIVE", "benchmark": "SPY"},
    "XLY": {"name": "Consumer Disc", "type": "GROWTH", "benchmark": "SPY"},
    "XLRE": {"name": "Real Estate", "type": "DEFENSIVE", "benchmark": "SPY"},
    "IYT": {"name": "Transportation", "type": "CYCLICAL", "benchmark": "XLI"},
    "XLU": {"name": "Utilities", "type": "DEFENSIVE", "benchmark": "SPY"},
    "XLI": {"name": "Industrials", "type": "CYCLICAL", "benchmark": "SPY"}
}

# Core liquid universe mapped to sectors & sub-sectors
TICKER_TAXONOMY = {
    # TECH SOFTWARE
    "MSFT": ("TECH SOFTWARE", "Enterprise Cloud & OS"),
    "PLTR": ("TECH SOFTWARE", "Data Analytics & AI Platforms"),
    "CRWD": ("TECH SOFTWARE", "Cloud Endpoint Cybersecurity"),
    "PANW": ("TECH SOFTWARE", "Enterprise Cybersecurity"),
    "ZS": ("TECH SOFTWARE", "Cloud Security & Zero Trust"),
    "DDOG": ("TECH SOFTWARE", "Cloud Observability & Monitoring"),
    "SNOW": ("TECH SOFTWARE", "Cloud Data Platform Software"),
    "MSTR": ("TECH SOFTWARE", "Enterprise Analytics & Treasury"),
    "ZETA": ("TECH SOFTWARE", "Marketing Automation & AI"),
    "DOCU": ("TECH SOFTWARE", "e-Signature & Agreement Cloud"),
    "NET": ("TECH SOFTWARE", "Edge Cloud & Web Infrastructure"),
    "ADBE": ("TECH SOFTWARE", "Creative Software & Digital Media"),
    "ORCL": ("TECH SOFTWARE", "Database & Cloud Infrastructure"),
    "NOW": ("TECH SOFTWARE", "Enterprise Workflow Automation"),
    "CRM": ("TECH SOFTWARE", "Enterprise Customer CRM"),
    "WDAY": ("TECH SOFTWARE", "Enterprise HCM & Financials"),
    "TEAM": ("TECH SOFTWARE", "Team Collaboration Software"),
    "ADSK": ("TECH SOFTWARE", "Design & 3D Engineering Software"),
    "ZM": ("TECH SOFTWARE", "Unified Video Communications"),
    "IOT": ("TECH SOFTWARE", "Connected Operations Cloud"),
    "DT": ("TECH SOFTWARE", "Software Observability & APM"),
    "ESTC": ("TECH SOFTWARE", "Search & Observability Software"),
    "FSLY": ("TECH SOFTWARE", "Edge Cloud & CDN"),
    "HPE": ("TECH SOFTWARE", "Enterprise Edge & Cloud Compute"),
    "BSY": ("TECH SOFTWARE", "Infrastructure Engineering Software"),
    "SHOP": ("TECH SOFTWARE", "E-Commerce Operating Platform"),
    "U": ("TECH SOFTWARE", "Interactive 3D Engine"),

    # TECH SEMIS
    "NVDA": ("TECH SEMIS", "AI Compute & Accelerated Graphics"),
    "AVGO": ("TECH SEMIS", "Broadband & Enterprise Networking"),
    "AMD": ("TECH SEMIS", "CPUs & Data Center GPUs"),
    "QCOM": ("TECH SEMIS", "Mobile & Edge Processors"),
    "TXN": ("TECH SEMIS", "Analog & Embedded Processing"),
    "ADI": ("TECH SEMIS", "Analog & Mixed-Signal ICs"),
    "MU": ("TECH SEMIS", "DRAM & NAND Memory"),
    "LRCX": ("TECH SEMIS", "Wafer Fabrication Equipment"),
    "AMAT": ("TECH SEMIS", "Materials Engineering & Semis"),
    "KLAC": ("TECH SEMIS", "Semiconductor Process Control"),
    "MRVL": ("TECH SEMIS", "Data Infrastructure Semiconductors"),
    "QRVO": ("TECH SEMIS", "RF Connectivity & Power"),
    "SWKS": ("TECH SEMIS", "Mobile Connectivity Chips"),
    "SNDK": ("TECH SEMIS", "Solid State Storage"),
    "AXTI": ("TECH SEMIS", "Compound Semiconductor Substrates"),

    # TECH CORE & HARDWARE
    "AAPL": ("TECH CORE", "Consumer Electronics & Services"),
    "DELL": ("TECH CORE", "Enterprise Servers & Compute"),
    "HPQ": ("TECH CORE", "Personal Systems & Printing"),
    "SMCI": ("TECH CORE", "High-Density AI Server Architecture"),
    "VRSN": ("TECH CORE", "Domain Name Registry Infrastructure"),
    "CLS": ("TECH CORE", "Electronic Manufacturing Services"),
    "TEL": ("TECH CORE", "Electronic Connectors & Sensors"),
    "JBL": ("TECH CORE", "Electronic Manufacturing Solutions"),
    "HSAI": ("TECH CORE", "Automotive LiDAR Sensors"),
    "VSAT": ("TECH CORE", "Satellite Broadband Services"),

    # FINANCIALS
    "JPM": ("FINANCIALS", "Diversified Mega-Bank"),
    "BAC": ("FINANCIALS", "Diversified Commercial Banking"),
    "WFC": ("FINANCIALS", "Consumer & Commercial Banking"),
    "C": ("FINANCIALS", "Global Corporate & Retail Banking"),
    "MS": ("FINANCIALS", "Investment Banking & Wealth Management"),
    "GS": ("FINANCIALS", "Global Banking & Markets"),
    "BRK.B": ("FINANCIALS", "Diversified Financial Holding"),
    "PNC": ("FINANCIALS", "Regional Banking Franchise"),
    "USB": ("FINANCIALS", "Diversified Regional Banking"),
    "COF": ("FINANCIALS", "Consumer Credit & Banking"),
    "AXP": ("FINANCIALS", "Global Payment Network & Credit"),
    "V": ("FINANCIALS", "Global Payments Processing"),
    "MA": ("FINANCIALS", "Global Payments Technology"),
    "HOOD": ("FINANCIALS", "Retail Brokerage & FinTech"),
    "SOFI": ("FINANCIALS", "Digital Banking & Lending"),
    "RKT": ("FINANCIALS", "Mortgage Origination & FinTech"),
    "AFRM": ("FINANCIALS", "Buy-Now-Pay-Later FinTech"),
    "SPGI": ("FINANCIALS", "Financial Ratings & Benchmarks"),
    "MCO": ("FINANCIALS", "Credit Ratings & Analytics"),
    "ICE": ("FINANCIALS", "Market Exchanges & Mortgage Tech"),
    "CBOE": ("FINANCIALS", "Options & Volatility Exchanges"),
    "STT": ("FINANCIALS", "Custody Banking & Asset Servicing"),
    "PRU": ("FINANCIALS", "Life Insurance & Asset Management"),
    "MET": ("FINANCIALS", "Institutional Insurance & Benefits"),
    "AJG": ("FINANCIALS", "Commercial Insurance Brokerage"),
    "RJF": ("FINANCIALS", "Wealth Management & Advisory"),
    "BX": ("FINANCIALS", "Alternative Asset Management"),
    "KKR": ("FINANCIALS", "Global Private Equity & Credit"),

    # HEALTHCARE
    "LLY": ("HEALTHCARE", "Pharmaceuticals & Incretins"),
    "JNJ": ("HEALTHCARE", "Pharmaceuticals & MedTech"),
    "UNH": ("HEALTHCARE", "Managed Care & Optum Health"),
    "ABBV": ("HEALTHCARE", "Biopharmaceuticals & Immunology"),
    "MRK": ("HEALTHCARE", "Oncology & Vaccines"),
    "PFE": ("HEALTHCARE", "Biopharmaceuticals"),
    "TMO": ("HEALTHCARE", "Life Sciences Instruments"),
    "ABT": ("HEALTHCARE", "Diagnostics & Medical Devices"),
    "DHR": ("HEALTHCARE", "Life Sciences & Diagnostics"),
    "ISRG": ("HEALTHCARE", "Robotic Surgical Systems"),
    "SYK": ("HEALTHCARE", "Orthopedics & Medical Devices"),
    "HUM": ("HEALTHCARE", "Medicare Advantage & Managed Care"),
    "ELV": ("HEALTHCARE", "Health Benefits & Managed Care"),
    "CI": ("HEALTHCARE", "Global Health Services & Evernorth"),
    "CVS": ("HEALTHCARE", "Pharmacy Care & Aetna Health"),
    "GILD": ("HEALTHCARE", "Antiviral Therapeutics & Oncology"),
    "BIIB": ("HEALTHCARE", "Neuroscience Biopharmaceuticals"),
    "MRNA": ("HEALTHCARE", "mRNA Vaccines & Therapeutics"),
    "IQV": ("HEALTHCARE", "Clinical Research & Healthcare Analytics"),
    "DVA": ("HEALTHCARE", "Kidney Dialysis Services"),
    "GRAL": ("HEALTHCARE", "Early Cancer Detection Diagnostics"),
    "OSCR": ("HEALTHCARE", "Health Insurance Technology"),
    "CRCL": ("HEALTHCARE", "Medical Technologies"),
    "TEM": ("HEALTHCARE", "AI Precision Medicine Diagnostics"),

    # ENERGY
    "XOM": ("ENERGY", "Integrated Global Oil & Gas"),
    "CVX": ("ENERGY", "Integrated Global Energy"),
    "COP": ("ENERGY", "Upstream Exploration & Production"),
    "EOG": ("ENERGY", "Shale Exploration & Production"),
    "SLB": ("ENERGY", "Global Oilfield Technology & Services"),
    "DVN": ("ENERGY", "Multi-Basin Oil & Gas E&P"),
    "FANG": ("ENERGY", "Permian Basin Pure-Play E&P"),
    "OXY": ("ENERGY", "Exploration & Carbon Capture"),
    "VLO": ("ENERGY", "Petroleum Refining & Biofuels"),
    "WMB": ("ENERGY", "Natural Gas Pipeline Infrastructure"),
    "BTU": ("ENERGY", "Thermal & Metallurgical Coal"),
    "PTEN": ("ENERGY", "Contract Drilling & Pressure Pumping"),
    "AMR": ("ENERGY", "Metallurgical Coal Mining"),
    "OII": ("ENERGY", "Subsea Engineering & Offshore Energy"),

    # INDUSTRIALS
    "GE": ("INDUSTRIALS", "Aerospace Propulsion & Systems"),
    "CAT": ("INDUSTRIALS", "Construction & Mining Machinery"),
    "DE": ("INDUSTRIALS", "Agricultural & Construction Tech"),
    "HON": ("INDUSTRIALS", "Diversified Industrial & Automation"),
    "UNP": ("INDUSTRIALS", "Class I Freight Railroad"),
    "CSX": ("INDUSTRIALS", "Eastern Rail Freight Network"),
    "NSC": ("INDUSTRIALS", "Rail Freight Transportation"),
    "FDX": ("INDUSTRIALS", "Global Express Freight & Logistics"),
    "UPS": ("INDUSTRIALS", "Package Delivery & Supply Chain"),
    "URI": ("INDUSTRIALS", "Industrial Equipment Rental"),
    "FAST": ("INDUSTRIALS", "Industrial Fasteners & Supply Chain"),
    "CPRT": ("INDUSTRIALS", "Online Salvage Vehicle Auctions"),
    "RSG": ("INDUSTRIALS", "Non-Hazardous Waste Services"),
    "WM": ("INDUSTRIALS", "Comprehensive Waste Management"),
    "VRT": ("INDUSTRIALS", "Data Center Thermal & Power Architecture"),
    "BE": ("INDUSTRIALS", "Solid Oxide Clean Fuel Cells"),

    # CONSUMER DISCRETIONARY
    "AMZN": ("CONSUMER DISC", "E-Commerce Infrastructure & Cloud"),
    "TSLA": ("CONSUMER DISC", "Electric Vehicles & Energy Storage"),
    "HD": ("CONSUMER DISC", "Home Improvement Retail"),
    "MCD": ("CONSUMER DISC", "Global QSR Franchise"),
    "SBUX": ("CONSUMER DISC", "Specialty Coffee Roaster & Retail"),
    "NKE": ("CONSUMER DISC", "Athletic Footwear & Apparel"),
    "ROST": ("CONSUMER DISC", "Off-Price Retail Stores"),
    "YUM": ("CONSUMER DISC", "Multi-Brand Fast Food Restaurants"),
    "CMG": ("CONSUMER DISC", "Fast-Casual Dining"),
    "F": ("CONSUMER DISC", "Automotive & Commercial Trucks"),
    "GM": ("CONSUMER DISC", "Automotive & Connected Fleets"),
    "RIVN": ("CONSUMER DISC", "Adventure Electric Vehicles"),
    "MELI": ("CONSUMER DISC", "Latin American E-Commerce & FinTech"),
    "ABNB": ("CONSUMER DISC", "Alternative Lodging & Experiences"),
    "ANF": ("CONSUMER DISC", "Lifestyle Apparel Retail"),

    # CONSUMER STAPLES
    "WMT": ("CONSUMER STAPLES", "Omnichannel Supercenter Retail"),
    "COST": ("CONSUMER STAPLES", "Membership Warehouse Clubs"),
    "PG": ("CONSUMER STAPLES", "Personal & Household Products"),
    "KO": ("CONSUMER STAPLES", "Non-Alcoholic Beverage Leader"),
    "PEP": ("CONSUMER STAPLES", "Beverages & Convenient Foods"),
    "MDLZ": ("CONSUMER STAPLES", "Global Snack & Confectionery"),
    "CL": ("CONSUMER STAPLES", "Oral & Personal Hygiene Products"),
    "KMB": ("CONSUMER STAPLES", "Personal Care Paper Products"),
    "DG": ("CONSUMER STAPLES", "Rural Discount Variety Stores"),
    "DLTR": ("CONSUMER STAPLES", "Consumable Value Retail"),
    "KR": ("CONSUMER STAPLES", "Supermarket & Grocery Retail"),
    "CHD": ("CONSUMER STAPLES", "Specialty Household Products"),
    "ELF": ("CONSUMER STAPLES", "Cosmetics & Skincare"),
    "MO": ("CONSUMER STAPLES", "Smokeable & Oral Tobacco Products"),

    # COMM SERVICES
    "GOOGL": ("COMM SERVICES", "Search, Cloud & AI Computing"),
    "META": ("COMM SERVICES", "Social Platforms & Metaverse"),
    "NFLX": ("COMM SERVICES", "Global Subscription Streaming"),
    "DIS": ("COMM SERVICES", "Entertainment, Studios & Parks"),
    "CMCSA": ("COMM SERVICES", "Broadband, Cable & Media"),
    "T": ("COMM SERVICES", "Telecommunications & 5G Network"),
    "VZ": ("COMM SERVICES", "Wireless Telecom Infrastructure"),
    "RBLX": ("COMM SERVICES", "Immersive Multiplayer Gaming Platform"),
    "RDDT": ("COMM SERVICES", "Community Forums & Social Discourse"),
    "SPOT": ("COMM SERVICES", "Audio Streaming & Podcasts"),
    "IRDM": ("COMM SERVICES", "Satellite Voice & Data Network"),
    "MGNI": ("COMM SERVICES", "Omnichannel Sell-Side AdTech"),
    "Z": ("COMM SERVICES", "Real Estate Technology Platform"),

    # REAL ESTATE & UTILITIES
    "PLD": ("REAL ESTATE", "Logistics & Industrial Warehousing"),
    "AMT": ("REAL ESTATE", "Wireless Communication Towers"),
    "EQIX": ("REAL ESTATE", "Global Interconnection Data Centers"),
    "DLR": ("REAL ESTATE", "Enterprise Colocation Data Centers"),
    "CEG": ("UTILITIES", "Nuclear & Zero-Carbon Generation"),
    "NEE": ("UTILITIES", "Regulated Electric & Clean Energy"),
    "SRE": ("UTILITIES", "Regulated Energy Infrastructure"),

    # MATERIALS & DEFENSE
    "LIN": ("MATERIALS", "Industrial Gases & Engineering"),
    "SHW": ("MATERIALS", "Coatings, Paints & Finishes"),
    "CF": ("MATERIALS", "Nitrogen Fertilizer & Clean Ammonia"),
    "NUE": ("MATERIALS", "Steel Products & Scrap Recycling"),
    "LMT": ("DEFENSE", "Aeronautics & Defense Systems"),
    "RTX": ("DEFENSE", "Aerospace Systems & Defense Avionics"),
    "NOC": ("DEFENSE", "Aeronautics & Space Systems"),
    "GD": ("DEFENSE", "Marine Systems & Combat Vehicles"),

    # CRYPTO / DIGITAL ASSETS
    "COIN": ("CRYPTO", "Digital Asset Exchange & Custody"),
    "RIOT": ("CRYPTO", "Bitcoin Mining Infrastructure"),
    "CIFR": ("CRYPTO", "Industrial Scale Crypto Mining"),
    "WULF": ("CRYPTO", "Zero-Carbon Digital Asset Mining"),
    "IREN": ("CRYPTO", "Next-Gen Data Centers & Bitcoin Mining")
}

def get_full_universe():
    """Returns sorted unique tickers across universe + ETFs."""
    tickers = set(TICKER_TAXONOMY.keys()).union(set(SECTOR_ETFS.keys()))
    tickers.add("SPY")
    return sorted(list(tickers))
